services:
    _defaults: { autowire: true, autoconfigure: true, public: true }

    # Contao frontend module Markocupic\RszSponsorenBundle\Controller\FrontendModule\RszSponsorenListingModuleController
    Markocupic\RszSponsorenBundle\Controller\FrontendModule\RszSponsorenListingModuleController:
        tags:
            - { name: contao.frontend_module, category: rsz_frontend_modules, template: mod_rsz_sponsoren_listing_module, type: rsz_sponsoren_listing_module }
            - { name: container.service_subscriber }
        public: true

