services:
    _defaults:
        autowire: true,
        autoconfigure: true,
        public: true

    Markocupic\RszSponsorenBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,ContaoManager}
